apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.argocdNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.helmchartsRepoUrl | quote }}
    path: {{ .Values.helmChartPath | quote }}
    targetRevision: {{ .Values.helmchartsTargetRevision | quote }}
    helm:
      values: |
        image:
          repository: {{ .Values.ecrRepositoryUrl | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.k8sNamespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
